import { Prompt } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const prompt = Prompt({
  weight: "400",
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en" className={prompt.className}>
        <body
        // className={`${prompt.variable} antialiased`} //this line make error hard to fix it
        >
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
