export const UserData = [
  {
    id: "user_2wg86rkgufx2ICK6kdo6GanHtke",
    object: "user",
    username: null,
    first_name: "Watanyu",
    last_name: "Onnum",
    image_url:
      "https://img.clerk.com/eyJ0eXBlIjoicHJveHkiLCJzcmMiOiJodHRwczovL2ltYWdlcy5jbGVyay5kZXYvb2F1dGhfZ29vZ2xlL2ltZ18yd2c4NnJPT1l4ZEpOVnBWZEQ4OVdYWVE5VGkifQ",
    has_image: true,
    primary_email_address_id: "idn_2wg86P3cDxpn0ooThbTS8OAWgdg",
    primary_phone_number_id: null,
    primary_web3_wallet_id: null,
    password_enabled: false,
    two_factor_enabled: false,
    totp_enabled: false,
    backup_code_enabled: false,
    email_addresses: [
      {
        id: "idn_2wg86P3cDxpn0ooThbTS8OAWgdg",
        object: "email_address",
        email_address: "ipae.wo@gmail.com",
        reserved: false,
        verification: {
          status: "verified",
          strategy: "from_oauth_google",
          attempts: null,
          expire_at: null,
        },
        linked_to: [
          {
            type: "oauth_google",
            id: "idn_2wg86TVqdfgknlbUJV4PVqKbjJn",
          },
        ],
        matches_sso_connection: false,
        created_at: 1746451680297,
        updated_at: 1746451683017,
      },
    ],
    phone_numbers: [],
    web3_wallets: [],
    passkeys: [],
    external_accounts: [
      {
        object: "external_account",
        id: "eac_2wg86RIavQw81dTQDHrGyQfptUx",
        provider: "oauth_google",
        identification_id: "idn_2wg86TVqdfgknlbUJV4PVqKbjJn",
        provider_user_id: "106619921345846382306",
        approved_scopes:
          "email https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile openid profile",
        email_address: "ipae.wo@gmail.com",
        first_name: "Watanyu",
        last_name: "Onnum",
        avatar_url:
          "https://lh3.googleusercontent.com/a/ACg8ocKNQ-tOtQEKGy5_RcMLhIqbcBrtn8ROgGw9mM8chkK1cUYiaT8=s1000-c",
        image_url:
          "https://img.clerk.com/eyJ0eXBlIjoicHJveHkiLCJzcmMiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQ2c4b2NLTlEtdE90UUVLR3k1X1JjTUxoSXFiY0JydG44Uk9nR3c5bU04Y2hrSzFjVVlpYVQ4PXMxMDAwLWMiLCJzIjoiUEhhVWNuV0syMklHektwREZFbTU0Z0xBL0tMd3RORjdJOWFyM0s2d0hCUSJ9",
        username: null,
        phone_number: null,
        public_metadata: {},
        label: null,
        created_at: 1746451680291,
        updated_at: 1746451680291,
        verification: {
          status: "verified",
          strategy: "oauth_google",
          attempts: null,
          expire_at: 1746452269160,
        },
      },
    ],
    saml_accounts: [],
    enterprise_accounts: [],
    public_metadata: {},
    private_metadata: {},
    unsafe_metadata: {},
    external_id: null,
    last_sign_in_at: 1746451683023,
    banned: false,
    locked: false,
    lockout_expires_in_seconds: null,
    verification_attempts_remaining: 100,
    created_at: 1746451683006,
    updated_at: 1746451683042,
    delete_self_enabled: true,
    create_organization_enabled: true,
    last_active_at: 1746451683005,
    mfa_enabled_at: null,
    mfa_disabled_at: null,
    legal_accepted_at: null,
    profile_image_url:
      "https://images.clerk.dev/oauth_google/img_2wg86rOOYxdJNVpVdD89WXYQ9Ti",
  },
  {
    id: "user_2wfXys44V3zU72On7BpvOefpC6K",
    object: "user",
    username: null,
    first_name: "วทัญญู",
    last_name: "อ่อนนุ่ม",
    image_url:
      "https://img.clerk.com/eyJ0eXBlIjoicHJveHkiLCJzcmMiOiJodHRwczovL2ltYWdlcy5jbGVyay5kZXYvb2F1dGhfZ29vZ2xlL2ltZ18yd2ZYeXRtQnRFVWZIRE5vMlF6SlpJV3lwdDYifQ",
    has_image: true,
    primary_email_address_id: "idn_2wfXyVe5vbI4dkMofqnzPjQuehi",
    primary_phone_number_id: null,
    primary_web3_wallet_id: null,
    password_enabled: false,
    two_factor_enabled: false,
    totp_enabled: false,
    backup_code_enabled: false,
    email_addresses: [
      {
        id: "idn_2wfXyVe5vbI4dkMofqnzPjQuehi",
        object: "email_address",
        email_address: "adamcorktail@gmail.com",
        reserved: false,
        verification: {
          status: "verified",
          strategy: "from_oauth_google",
          attempts: null,
          expire_at: null,
        },
        linked_to: [
          {
            type: "oauth_google",
            id: "idn_2wfe90QDFvmfTEvmGtIICdTPyb2",
          },
        ],
        matches_sso_connection: false,
        created_at: 1746433856830,
        updated_at: 1746433859725,
      },
    ],
    phone_numbers: [],
    web3_wallets: [],
    passkeys: [],
    external_accounts: [
      {
        object: "external_account",
        id: "eac_2wfe90KW5nJb61bN8tKsnHzFcdv",
        provider: "oauth_google",
        identification_id: "idn_2wfe90QDFvmfTEvmGtIICdTPyb2",
        provider_user_id: "101997380528756384367",
        approved_scopes:
          "email https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile openid profile",
        email_address: "adamcorktail@gmail.com",
        first_name: "วทัญญู",
        last_name: "อ่อนนุ่ม",
        avatar_url:
          "https://lh3.googleusercontent.com/a/ACg8ocKrU4-y_YS7Pt5rf7tBPk16May37Ym9jcNxNlLPTcRa9NZuxRw=s1000-c",
        image_url:
          "https://img.clerk.com/eyJ0eXBlIjoicHJveHkiLCJzcmMiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQ2c4b2NLclU0LXlfWVM3UHQ1cmY3dEJQazE2TWF5MzdZbTlqY054TmxMUFRjUmE5Tlp1eFJ3PXMxMDAwLWMiLCJzIjoiNCtEVUJveUFpbEZiUjVVVDI2MlVRdlZQSzZnUTMwZGxURHJWS1lFSU82OCJ9",
        username: "",
        phone_number: "",
        public_metadata: {},
        label: null,
        created_at: 1746436899671,
        updated_at: 1746443616603,
        verification: {
          status: "verified",
          strategy: "oauth_google",
          attempts: null,
          expire_at: 1746437493049,
        },
      },
    ],
    saml_accounts: [],
    enterprise_accounts: [],
    public_metadata: {},
    private_metadata: {},
    unsafe_metadata: {},
    external_id: null,
    last_sign_in_at: 1746443616615,
    banned: false,
    locked: false,
    lockout_expires_in_seconds: null,
    verification_attempts_remaining: 100,
    created_at: 1746433859718,
    updated_at: 1746451660657,
    delete_self_enabled: true,
    create_organization_enabled: true,
    last_active_at: 1746433859717,
    mfa_enabled_at: null,
    mfa_disabled_at: null,
    legal_accepted_at: null,
    profile_image_url:
      "https://images.clerk.dev/oauth_google/img_2wfXytmBtEUfHDNo2QzJZIWypt6",
  },
];
